linters-settings:
  custom:
    robustruct:
      type: "module"
      settings:
        features:
          - fields_require
          - fields_align
        flags:
          - disable_test

linters:
  enable:
    - robustruct
