linters-settings:
  custom:
    robustruct:
      type: "module"
      settings:
        features:
          - "fields_require"
          - "fields_align"
          - "const_group_switch_cover"
        flags:
          - disable_test

linters:
  enable:
    - robustruct
