// Code generated by variant; DO NOT EDIT.
package account

import "fmt"

type Account int

const (
	zero  Account = 0
	Admin Account = iota
	User  Account = iota
	Guest Account = iota
)

func Values() []string {
	return []string{"admin", "user", "guest"}
}
func (Account) Values() []string {
	return []string{"admin", "user", "guest"}
}

func Default() Account    { return Guest }
func NewDefault() Account { return Guest }
func NewAdmin() Account   { return Admin }
func NewUser() Account    { return User }
func NewGuest() Account   { return Guest }

func (e Account) IsAdmin() bool { return e == Admin }
func (e Account) IsUser() bool  { return e == User }
func (e Account) IsGuest() bool { return e == Guest || e == zero }

func (e Account) String() string {
	switch e {
	case Admin:
		return "admin"
	case User:
		return "user"
	case Guest:
		return "guest"
	default:
		return "guest"
	}
}

func FromString(s string) (Account, error) {
	switch s {
	case "admin":
		return Admin, nil
	case "user":
		return User, nil
	case "guest":
		return Guest, nil
	default:
		return zero, fmt.Errorf("invalid Account: %s", s)
	}
}
