name: Build and Run
on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: go.sum

      - name: Build
        run: |
          cd setup
          make build
          make install

      - name: Run
        run: |
          golangci-lint run
