name: Go Generate and Push
on:
  push:
    branches: 
      - '**'

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: go.sum

      - name: Generate
        run: |
          go generate ./...

      - name: Commit and Push if changes
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
          else
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add --all
            git commit -m "$ go generate ./..."
            git push origin
          fi
