name: Update pkg.go.dev documentation
on:
  release:
    types: [created]
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request pkg.go.dev documentation update
        run: |
          curl -X POST https://pkg.go.dev/fetch/github.com/ysuzuki19/robustruct@${{ github.event.release.tag_name }}
