name: Test
on:
  push:
    branches: 
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: go.sum

      - name: Run tests
        run: go test ./...
